spring:
    mvc.view.suffix: .htmlsec
    datasource:
        #url: "jdbc:postgresql://localhost:5432/postgres"
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USERNAME}
        password: ${PROD_DB_PASSWORD}
        #username: postgres
        #password: admin123
    jpa:
        hibernate.ddl-auto: update
        #properties.hibernate.format_sql: true
        #properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQL81Dialect"
    
    mail:
        host: smtp.googlemail.com
        port: 587
        username: zavrsni257@gmail.com
        password: rcnorsbaclaiiqxo
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true

    servlet:
        multipart.max-file-size: 1000MB
        multipart.max-request-size: 1000MB

    data:
        redis:
            host: localhost
            port: 6379


        
server.port: 9041
