spring:
    mvc.view.suffix: .htmlsec
    datasource:
        # url: "jdbc:postgresql://localhost:5432/postgres"
        url: "jdbc:postgresql://c9tiftt16dc3eo.cluster-czz5s0kz4scl.eu-west-1.rds.amazonaws.com:5432/d1omm4aqj3e4bc"
        #username: ${PROD_DB_USERNAME}
        #password: ${PROD_DB_PASSWORD}
        # username: postgres
        # password: admin123
        username: ud5c8ih6i4smt2
        password: p229d85b1fbb9612d8d23e40c081de5472d252c4483633fc7ef6ca4b0c8f20cd5
    jpa:
        hibernate.ddl-auto: update
        #properties.hibernate.format_sql: true
        #properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQL81Dialect"
    
    mail:
        host: smtp.googlemail.com
        port: 587
        username: zavrsni257@gmail.com
        password: rcnorsbaclaiiqxo
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true

    servlet:
        multipart.max-file-size: 1000MB
        multipart.max-request-size: 1000MB

    data:
        redis:
            host: localhost
            port: 6379


        
server.port: 9041

cloud:
    aws:
        credentials:
            access-key: AKIASPOEHCP2XZBGASFJ
            secret-key: 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
        region:
            static: eu-north-1
        stack:
            auto: false

application:
    bucket:
        name: zavrsni